[package]
name = "guitar-tuner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
biquad = "0.5.0"
clap = { version = "4.5", features = ["derive"] }
# cpal = { version = "0.15.3", features = ["jack"] }
cpal = { version = "0.15.3" }
ringbuf = "0.4.7"
